FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y libstdc++6 && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /results

WORKDIR /app

COPY build/test ./matching_engine

RUN chmod +x ./matching_engine

CMD ./matching_engine 2>&1 | tee /results/output.log